### ISSUE TITLE
Flexibility on Other Windows processes vs Just for Kodi

### ISSUE THREAD

**Issue by TheEngineerGuy** [fandangos/AutoHDR#1]
Is possible that this be modified for launching other windows programs in HDR as well, and no just be strictly for Kodi? For instance certain Games that require windows HDR to be toggled on.

**Comment by fandangos** [comment]
Sure.

Just look at hdr switcher on my git.
https://github.com/fandangos/hdr-switcher
It's an exe that will put your monitor in hdr mode using nvidia api.
If you just want hdr to be turned on you can use windows display settings and turn it on.

**Comment by TheEngineerGuy** [comment]
Windows Toggle is just annoying to enable before launching and disable after ending a game. If I leave it on for ever, the whites are way over blown on windows UI. Just a mess.

Thank you. I will take a look at that. 

I am not sure what in addition to putting monitor in HDR does the windows HDR toggle performs. Will hdr-switcher do the same thing as enabling the toggle from windows?

**Comment by fandangos** [comment]
No it will enable hdr using the nvidia api so it won't use windows side of hdr.

It's the way games do. If you download from steam and not windows store.

**Comment by TheEngineerGuy** [comment]
ok. You hit the nail on the head there. My problem is windows store games :). So, if I use this, Windows Store games should run in HDR right?

**Comment by fandangos** [comment]
This is very setup dependent.
If you are trying to stream using nvidia streaming it might give you all kind of problems.

I used it to fix resident evil 3.. but it's a pain.

**Comment by TheEngineerGuy** [comment]
I am not a streamer :). So, I am hoping this would do the trick for me then.

**Comment by TheEngineerGuy** [comment]
thanks again for responding so quickly my friend.

**Comment by fandangos** [comment]
I was talking about streaming the game from your pc to a nvidia shield, which is something I used the switcher.

No problem. Hope it helps you.

**Comment by TheEngineerGuy** [comment]
O I see. No I have a long HDMI run. I don't use streaming, as it softens the colours a bit. All good. Will let you know if I run into something.

**Comment by TheEngineerGuy** [comment]
Tried it with RDR2. Not sure how the damn thing uses HDR, but it works fine when Windows Toggle to HDR is enabled. When Windows toggle is disabled and I use HDRSwitcher (which enables HDR correctly), RDR2 turns off HDR on game launch.

I am guessing it is tied to the windows API somehow. So, unless this switcher can be tied to Windows API, I may have to use a VBScript to toggle on and off.

**Comment by fandangos** [comment]
Put the switched in your desktop.
Add a shortcut to it and try to launch it during gameplay.

**Comment by TheEngineerGuy** [comment]
Yep, that did the trick. Now, is there a way to turn it off with this binary after game exit

**Comment by fandangos** [comment]
It might be possible to compile it to turn it off but it will turn hdr off when it's closed.
